#!/usr/bin/env python3
"""Generate <Internal Artifacts>/specs/_index.md: one line per feature spec.

Usage:
  spec_index.py <slug>            # write specs/_index.md
  spec_index.py <slug> --print    # print it instead

VanPM reads this index before planning instead of opening every spec, then opens
only the specs that overlap. Generated from the spec files (the source of truth);
never edit _index.md by hand. tracker_push.py regenerates it after every push.

Folders: specs/*.md = active, specs/_done/ = merged + complete (archived by the
orchestrator's close-on-merge step), specs/_superseded/ = replaced and cancelled.
Standard library only.
"""
import datetime, importlib.util, json, os, re, sys

WS = "/home/openclaw/.openclaw/workspace"
VALIDATOR = f"{WS}/projects/_tools/validate_context.py"
PUSH = f"{WS}/project-manager/skills/feature-breakdown/scripts/tracker_push.py"

NODE_RX = re.compile(r"node-id=([0-9]+[-:][0-9]+)")
ENDPOINT_RX = re.compile(r"\b(GET|POST|PATCH|PUT|DELETE)\s+(/api/[^\s`?,)]+)")
TABLE_RX = re.compile(r"`(\w+)`\s+table|\bto\s+`(\w+)`|`(\w+)\.\w+")
SHARED_UI_RX = re.compile(r"layout|shell|nav|sidebar|header|footer|modal", re.I)
OTHER_DEP_RX = re.compile(r"^- Depends on \(other feature\):\s*(.+)$", re.M)


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def summarize(path, push):
    tickets = push.parse_spec(path)
    parent = tickets[0]
    # `.tracker.json` going forward; markers written before the rename still resolve.
    marker_path = next((c for c in (path[:-3] + ".tracker.json", path[:-3] + ".clickup.json")
                        if os.path.exists(c)), path[:-3] + ".tracker.json")
    marker = json.load(open(marker_path)) if os.path.exists(marker_path) else {}
    pid = (marker.get(parent.get("title"), {}) or {}).get("id") or parent.get("existing_id")
    lanes = {}
    for t in tickets[1:]:
        lanes[t.get("lane", "?")] = lanes.get(t.get("lane", "?"), 0) + 1
    tables, endpoints, shared, deps = set(), set(), [], set()
    for t in tickets:
        body = t["body"]
        if t.get("lane") == "DB":
            text = push.section(body, "In scope") + push.section(body, "Technical notes")
            for m in TABLE_RX.finditer(text):
                tables.add(next(g for g in m.groups() if g))
        if t.get("lane") == "BE":
            for m in ENDPOINT_RX.finditer(t.get("title", "") + " " + push.section(body, "Technical notes")):
                endpoints.add(f"{m.group(1)} {m.group(2)}")
        if t.get("lane") == "FE" and SHARED_UI_RX.search(t.get("title", "")):
            shared.append(t["title"])
        for d in OTHER_DEP_RX.findall(body):
            deps.add(re.sub(r"\s*\([^)]*\)\s*$", "", d).strip())
    parts = [f"`{os.path.basename(path)}`", f"**{parent.get('title', '?')}**",
             f"ticket {pid}" if pid else "not pushed",
             "lanes " + " ".join(f"{k}{v}" for k, v in sorted(lanes.items()))]
    nodes = sorted(set(NODE_RX.findall(parent.get("figma", ""))))
    if nodes:
        parts.append("figma " + ", ".join(nodes))
    if tables:
        parts.append("tables " + ", ".join(sorted(tables)))
    if endpoints:
        parts.append("api " + ", ".join(sorted(endpoints)))
    if shared:
        parts.append("UI " + "; ".join(shared))
    if deps:
        parts.append("needs " + "; ".join(sorted(deps)))
    return "- " + " · ".join(parts)


def build(slug):
    vc = load(VALIDATOR, "vc")
    push = load(PUSH, "push")
    ctx_path = f"{WS}/projects/{slug}/PROJECT_CONTEXT.md"
    fields, errors = vc.parse(ctx_path)
    if errors:
        sys.exit("PROJECT_CONTEXT invalid: " + "; ".join(errors))
    specs = os.path.join(fields["artifacts_dir"], "specs")
    groups = {}
    for label, sub in (("Active", ""), ("Done (archived in `_done/`)", "_done"),
                       ("Superseded (cancelled, in `_superseded/`)", "_superseded")):
        d = os.path.join(specs, sub)
        files = sorted(f for f in os.listdir(d) if f.endswith(".md") and not f.startswith("_")) \
            if os.path.isdir(d) else []
        lines = []
        for f in files:
            try:
                lines.append(summarize(os.path.join(d, f), push))
            except SystemExit as e:  # parse_spec dies on malformed specs
                lines.append(f"- `{f}` · UNPARSEABLE: {e}")
        groups[label] = lines
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out = [f"# Spec index: {slug}", "",
           f"<!-- GENERATED by projects/_tools/spec_index.py at {now}. Do not edit; edit the specs. -->",
           "Read this before planning. Open a spec only if its figma screens, tables, api or UI overlap",
           "what you are about to plan. Planned (not built) columns: `_planned-data.md`. Built schema:",
           "the **Schema file** in PROJECT_CONTEXT.md.", ""]
    for label, lines in groups.items():
        out += [f"## {label} ({len(lines)})", ""] + (lines or ["- none"]) + [""]
    return os.path.join(specs, "_index.md"), "\n".join(out)


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    path, text = build(sys.argv[1])
    if "--print" in sys.argv:
        print(text)
        return
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {path} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
